[package]
name = "jsonrpc"
version = "0.1.0"
authors = ["Andrew Dirksen <andrew@dirksen.com>"]
edition = "2018"

[dependencies]
jsonrpc_proc_macro = { path = "./proc_macros" }
serde_json = "1"
serde = "1"
syn = "0.15.26"
jsonrpc-core = "10.0.1"

[dev-dependencies]
assert_matches = "1.3.0"
